"use client";
// app/(app)/reports/page.tsx
// VoC Reports — Real AI + Real DB Only

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { formatDate } from "@/lib/utils";
import Link from "next/link";
import type { Report } from "@/types";

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [title, setTitle] = useState("");
  const [periodDays, setPeriodDays] = useState(30);
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState("");
  const [feedbackPreview, setFeedbackPreview] = useState<number | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/reports");
      const json = await res.json();
      if (json.data) setReports(json.data);
    } catch (err) { console.error("Failed to fetch reports:", err); }
    finally { setLoading(false); }
  };

  const fetchFeedbackPreview = async (days: number) => {
    setPreviewLoading(true);
    setFeedbackPreview(null);
    try {
      const end = new Date();
      const start = new Date(end.getTime() - days * 24 * 60 * 60 * 1000);
      const res = await fetch(`/api/dashboard?dateFrom=${start.toISOString()}&dateTo=${end.toISOString()}`);
      const json = await res.json();
      if (json.data?.stats?.totalFeedback !== undefined) setFeedbackPreview(json.data.stats.totalFeedback);
    } catch { setFeedbackPreview(null); }
    finally { setPreviewLoading(false); }
  };

  useEffect(() => { fetchReports(); }, []);
  useEffect(() => { if (showGenerateModal) fetchFeedbackPreview(periodDays); }, [periodDays, showGenerateModal]);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title) return;
    setGenerateError(""); setGenerating(true);
    try {
      const end = new Date();
      const start = new Date(end.getTime() - periodDays * 24 * 60 * 60 * 1000);
      const res = await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, periodStart: start.toISOString(), periodEnd: end.toISOString() }),
      });
      const json = await res.json();
      if (!res.ok) { setGenerateError(json.error || "Failed to generate report."); return; }
      setTitle(""); setShowGenerateModal(false); setGenerateError(""); fetchReports();
    } finally { setGenerating(false); }
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-text-primary">Voice-of-Customer Reports</h1>
          <p className="text-xs text-text-muted mt-0.5">AI-synthesized VoC reports generated from real database feedback signals only</p>
        </div>
        <Button onClick={() => { setGenerateError(""); setShowGenerateModal(true); }} id="generate-report-btn"
          leftIcon={<svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" /></svg>}>
          Generate Report
        </Button>
      </div>

      <div className="flex items-start gap-3 p-4 rounded-2xl bg-violet-50/70 border border-violet-100 text-xs text-violet-800">
        <svg className="w-4 h-4 text-violet-500 mt-0.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <span><strong>Real data only.</strong> Reports are generated by Claude AI using exclusively your ingested customer feedback from the database. Reports cannot be generated for periods with no feedback.</span>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {Array.from({ length: 3 }).map((_, i) => (<div key={i} className="card p-5 h-48 animate-pulse bg-border-subtle" />))}
        </div>
      ) : reports.length === 0 ? (
        <EmptyState title="No VoC reports generated"
          description="Generate your first AI executive VoC report by selecting a period that contains real ingested feedback."
          icon={<svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>} />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {reports.map((report) => (
            <div key={report.id} className="card p-5 hover:shadow-card-hover transition-shadow flex flex-col justify-between space-y-4">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <span className="badge bg-accent-light text-accent text-[10px] uppercase tracking-wider">VoC Report</span>
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-violet-50 text-violet-600 border border-violet-100">AI</span>
                </div>
                <h3 className="text-base font-bold text-text-primary">{report.title}</h3>
                <p className="text-xs text-text-muted mt-1">Created {formatDate(report.createdAt)} by {report.generatedBy?.name ?? "User"}</p>
              </div>
              <div className="pt-3 border-t border-slate-100 flex items-center justify-between">
                <span className="text-xs text-slate-500 font-medium">{report.contentJson?.totalItems ?? 0} real signals</span>
                <Link href={`/reports/${report.id}`} className="text-xs font-bold text-indigo-600 hover:text-indigo-800 bg-indigo-50 hover:bg-indigo-100 px-3 py-1 rounded-full transition-colors">View &amp; Email →</Link>
              </div>
            </div>
          ))}
        </div>
      )}

      {showGenerateModal && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="card p-6 w-full max-w-md space-y-5 animate-fade-in">
            <div>
              <h3 className="text-lg font-bold text-text-primary">Generate AI VoC Report</h3>
              <p className="text-xs text-text-muted mt-1">Claude will analyze your real database feedback to produce an executive report.</p>
            </div>
            {generateError && (
              <div className="p-3.5 bg-rose-50 border border-rose-200 rounded-2xl text-xs text-rose-800 font-medium flex items-start gap-2.5">
                <svg className="w-4 h-4 text-rose-500 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                <span>{generateError}</span>
              </div>
            )}
            <form onSubmit={handleGenerate} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-text-primary mb-1">Report Title</label>
                <input type="text" required placeholder="e.g. Q3 VoC Executive Summary" value={title} onChange={(e) => setTitle(e.target.value)} className="input-base" />
              </div>
              <div>
                <label className="block text-sm font-medium text-text-primary mb-1">Time Period</label>
                <select value={periodDays} onChange={(e) => setPeriodDays(Number(e.target.value))} className="input-base">
                  <option value={7}>Last 7 Days</option>
                  <option value={14}>Last 14 Days</option>
                  <option value={30}>Last 30 Days</option>
                  <option value={90}>Last 90 Days</option>
                </select>
              </div>
              <div className={`p-3.5 rounded-2xl border text-xs font-medium flex items-center gap-2.5 ${
                previewLoading ? "bg-slate-50 border-slate-100 text-slate-500"
                : feedbackPreview === 0 ? "bg-amber-50 border-amber-200 text-amber-800"
                : feedbackPreview !== null && feedbackPreview > 0 ? "bg-emerald-50 border-emerald-200 text-emerald-800"
                : "bg-slate-50 border-slate-100 text-slate-400"
              }`}>
                {previewLoading ? <><svg className="w-4 h-4 animate-spin shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg><span>Checking database signals…</span></>
                : feedbackPreview === 0 ? <><svg className="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg><span><strong>No feedback found.</strong> Select a longer period or ingest feedback first.</span></>
                : feedbackPreview !== null ? <><svg className="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg><span><strong>{feedbackPreview.toLocaleString()} real signals</strong> ready — Claude AI will analyze these.</span></>
                : <span>Select a period to preview available signals.</span>}
              </div>
              <div className="flex justify-end gap-2 pt-2">
                <Button variant="secondary" onClick={() => { setShowGenerateModal(false); setGenerateError(""); }} type="button">Cancel</Button>
                <Button type="submit" loading={generating} id="confirm-generate-btn" disabled={feedbackPreview === 0 || previewLoading}>
                  {generating ? "AI Generating…" : "Generate with AI"}
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
